<h1>Formulario</h1>

<?Utils::mostrarError('register'); ?>

<?php
 if (isset($_GET['id'])) {
?>
<h1>Modificar pizza</h1>

<?php
$titulo = $oferta_selec->titulo;
$imagen = $oferta_selec->imagen;
$descripcion = $oferta_selec->descripcion;
?>

    <img width=300px src="<?=$imagen ?>">
    <form action="index.php?c=Ofertas&a=grabarOferta&id=<?=$id?>"  enctype="multipart/form-data" method="POST">
    Escoge una imagen:
    <input type="file" name="imagen" id="imagen">
<br><br>

<label for="titulo">Título</label>
<input type="text" value=<?=$titulo?> $titulo name="titulo" required /><br><br>

<label for="descripcion">Descripcion</label>
<input type="text" value="<?=$descripcion ?>" name="descripcion" required/><br><br>
<br>

<input type="submit" name="anadir" value="Añadir oferta">
</form>

<?php 
}
else { ?>

<h1>Añadir nueva oferta</h1>

<form action="index.php?c=Ofertas&a=grabarOferta"  enctype="multipart/form-data" method="POST">
    Escoge una imagen:
    <input type="file" name="imagen" id="imagen">
<br><br>

<label for="titulo">Título</label>
<input type="text" name="titulo" required /><br><br>

<label for="descripcion">Descripcion</label>
<input type="text"  name="descripcion" required/><br><br>
<br>

<input type="submit" name="anadir" value="Añadir oferta">
</form>

<?php }

?>