<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>PIZZERIA ALBERTI</title>
        <link rel="stylesheet" href="assets/css/estilo.css>">
    </head>
    <body>

<?php

while ($oferta = $todasOfertas->fetchObject()) {
    //var_dump($oferta);
    //var_dump($oferta->imagen);
    echo  "<h1>$oferta->titulo</h1><img width=200px height=200px src=$oferta->imagen>.<br>".$oferta->descripcion.".";

}
?>

    </body>
</html>