<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Principal de usuario</title>
        <link rel="stylesheet" href="assets/css/estilo.css>">
    </head>
    <body>
    <ul>

    <li><a href="index.php">Principal de usuario</a></li>
    <li><a href="index.php?c=Usuarios&a=TodosUsuarios">Ver todos los usuarios</a></li>
    <li><a href="index.php?c=Usuarios&a=registro">Crear usuarios</a></li>


    </ul>