<h1>Insertar notas</h1>

<?Utils::mostrarError('register'); ?>

<form action="index.php?c=Notas&a=save" method="POST">
<label for="usuario_id">Usuario</label>
<input type="number" name="usuario_id" required />

<label for="titulo">Título</label>
<input type="text" name="titulo" required />

<label for="descripcion">Descripcion</label>
<input type="text" name="descripcion" required/>

<input type="submit" name="anadir" value="Añadir nota" />
</form>